// Code generated by github.com/go-enry/go-enry/v2/internal/code-generator DO NOT EDIT.
// Extracted from github/linguist commit: f101af52dce8d8a8da53556d197472327d61b753

package data

// linguist's commit from which files were generated.
var LinguistCommit = "f101af52dce8d8a8da53556d197472327d61b753"
